### PR TITLE
Add dev dependencies from core/composer.json

### PR DESCRIPTION
**Pull request by damontgomery**
This allows PHPUnit tests to run. Also fixed some tabs.

### CODE REVIEW

**Comment by balsama** [comment]
@weitzman @grasmash Can one of you please give this pull request a quick sanity check? It makes sense, but @phenaproxima, who originally decided on the dev dependencies, isn't available to review and I want to make sure he didn't leave these out for a reason.

**Comment by phenaproxima** [comment]
I would rather not take this approach -- it means we're going to have to manually keep up with core's dev dependencies, and manually resolve version conflicts with our own dev dependencies (if we add any).

However, this is definitely something we need, so I think we should use the wikimedia merge plugin for this instead. That will take a bit more hacking, but is far more future-proof.

**Comment by damontgomery** [comment]
I tried to use the wikimedia merge plugin and was not able to get it to work. I kept getting duplicate class errors which could have been an autoloading issue.

I'll say what I always say with community contribution,

This may not be the ideal solution, but unless someone wants to work on that ideal solution, I would recommend we at least use the working non-ideal solution for now.

This could be easily updated if down the road someone with more experience with composer wanted to update it.

**Comment by phenaproxima** [comment]
@damontgomery: Understood and agreed. I would normally be the one to work on the ideal solution, but I'm out until the 20th.

@balsama: Given the circumstances, I'd be OK with merging this now as long as the issue remains open so that we can work on a more future-proof solution when I'm back.

**Comment by damontgomery** [comment]
@phenaproxima, I'm not saying this needs to get done in the next week, so please don't feel rushed. If there is a plan to address the issue within a reasonable time frame, I think that's ok.

If there are no plans to fix it (which does not seem to be the case), I'd recommend using the non-ideal method.

@phenaproxima, I'd love to see the correct way to address this so I can learn more about composer. Please copy me when you've made the updates. :) Thanks.

**Comment by weitzman** [comment]
IMO, keeping up with core's dependencies is not hard at all. They will be extremely infrequent on the 8.x branch and adapting to a change is a one line fix.

**Comment by balsama** [comment]
Ok. I merged this. Thanks for the input everyone.

**Comment by PieterDC** [comment]
(nowadays) you can also use require https://packagist.org/packages/webflo/drupal-core-require-dev instead of copying the individual packages over from Drupal core's composer.json to your distribution its composer.json file.

**Pull request merged**
